name: Build Executable (Windows)

on:
  push:
    branches:
      - main   # change to your branch if needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt ( pip install -r requirements.txt )
          pip install pyinstaller
          
      - name: Download and install Tesseract (Windows build)
        run: |
          Invoke-WebRequest -Uri "https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v5.3.0.20221214.exe" -OutFile tesseract-installer.exe
          Start-Process tesseract-installer.exe -ArgumentList "/SILENT" -Wait
          Write-Host "Tesseract installed to C:\Program Files\Tesseract-OCR"
          Get-ChildItem "C:\Program Files\Tesseract-OCR"

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile helper.py `
            --add-data "static;static" `
            --add-data "templates;templates" `
            --add-data "C:\Program Files\Tesseract-OCR;Tesseract-OCR"
            
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: helper-executable
          path: dist/helper.exe
